### ISSUE TITLE
compatible with older glib (< 2.60)

### ISSUE THREAD

**Issue by BLumia** [explorer-cs/peony-qt#8]
Current debian stable (buster) still only offer `libglib2.0` with `2.58.3` which doesn't provide interfaces like `g_app_info_launch_uris_async()`. But still would like to build and try it under  debian stable,  make it build under older glib only need a few tweaks which can be controlled by macro, would like to know if this is going to support or it will only support glib greater than `2.60` version.

Thanks a lot.

当前的 debian stable (buster) 仍然只提供了 2.58.3 版本的 libglib2.0 包，其中未包含目前此项目所用到的 `g_app_info_launch_uris_async()`接口。不过仍希望能够在 debian stable 中体验和跟进此项目。使此项目能够在旧版 glib 中编译只需要动一点点代码并通过 glib 提供的宏控制即可，所以想知道这种在旧版本中构建的需求是否会包含在以后此项目的直接支持中。

非常感谢。

Patch:

``` patch
diff --git a/libpeony-qt/file-launcher/file-launch-action.cpp b/libpeony-qt/file-launcher/file-launch-action.cpp
index 9eb6a40..8514d84 100644
--- a/libpeony-qt/file-launcher/file-launch-action.cpp
+++ b/libpeony-qt/file-launcher/file-launch-action.cpp
@@ -107,19 +107,27 @@ void FileLaunchAction::lauchFileAsync()
     }
 
     if (isDesktopFileAction()) {
+#if GLIB_CHECK_VERSION(2, 60, 0)
         g_app_info_launch_uris_async(m_app_info, nullptr,
                                      nullptr, nullptr,
                                      nullptr, nullptr);
+#else
+        g_app_info_launch_uris(m_app_info, nullptr, nullptr, nullptr);
+#endif // GLIB_CHECK_VERSION
     } else {
         GList *l = nullptr;
         char *uri = g_strdup(m_uri.toUtf8().constData());
         l = g_list_prepend(l, uri);
+#if GLIB_CHECK_VERSION(2, 60, 0)
         g_app_info_launch_uris_async(m_app_info,
                                      l,
                                      nullptr,
                                      nullptr,
                                      nullptr,
                                      nullptr);
+#else
+        g_app_info_launch_uris(m_app_info, l, nullptr, nullptr);
+#endif // GLIB_CHECK_VERSION
         g_list_free(l);
     }
```

**Comment by Yue-Lan** [comment]
Thanks for the feedback.

This patch is reasonable for matching glib-2.0 on debian stable. I will consider it.

However, there might be not only unprovided apis or 3rd-party libs in glib2.0 but aslo in qt5.
For example, the package qt5-gtk2-platformtheme (require qt5 version above 5.12), is aslo a very important package for this project (even though it's not a strong dependence). I guess qt5's version of buster is also lower than I expected.
So, I can't guarantee the perfect experience and development on buster.

感谢反馈，

这个patch对于debian stable的glib2.0是合理的，我会考虑它。

然而，不仅仅是glib的api，debian stable中也可能缺失qt5相关的api或者库；
举例而言，qt5-gtk2-platformtheme（要求qt5版本大于5.12）也是一个对于这个项目十分重要的软件包（即使它不是强依赖），我想buster上的qt5版本同样低于我的预期。
综上，我不能够保证你能够在buster上完美的体验或者基于这个项目进行开发。

**Comment by BLumia** [comment]
Thanks for the response. fyi i've tested your program with some other qpa plugin and it works pretty well on my machine, so i just wonder if we can make it also support glib2.0, great work btw :)

感谢回复，另外我在本机使用已安装的几个其它 qpa 插件测试了运行效果，效果看上去挺不错，glib2.0 低版本上构建需要做这个修改是目前遇到的唯一的小问题。期待后续跟进 :)

**Comment by Yue-Lan** [comment]
Greate!

Thanks for your good efforts to this project. Since you think the question is not difficult to resolve, I hope you can help me and make some patch for matching with your working environment.

Cheers.

很好，

感谢你的测试和工作，我希望你能够提供一些patch来帮助我解决你所关心的问题，当然我后续也会持续关注这些问题。

:D

**Comment by BLumia** [comment]
The patch already provided in the first floor of the issue but anyway here is the updated patch in case you missed it:

```
diff --git a/libpeony-qt/file-launcher/file-launch-action.cpp b/libpeony-qt/file-launcher/file-launch-action.cpp
index 08f12f4..cd6a673 100644
--- a/libpeony-qt/file-launcher/file-launch-action.cpp
+++ b/libpeony-qt/file-launcher/file-launch-action.cpp
@@ -112,19 +112,27 @@ void FileLaunchAction::lauchFileAsync(bool forceWithArg)
     }
 
     if (isDesktopFileAction() && !forceWithArg) {
+#if GLIB_CHECK_VERSION(2, 60, 0)
         g_app_info_launch_uris_async(m_app_info, nullptr,
                                      nullptr, nullptr,
                                      nullptr, nullptr);
+#else
+        g_app_info_launch_uris(m_app_info, nullptr, nullptr, nullptr);
+#endif // GLIB_CHECK_VERSION
     } else {
         GList *l = nullptr;
         char *uri = g_strdup(m_uri.toUtf8().constData());
         l = g_list_prepend(l, uri);
+#if GLIB_CHECK_VERSION(2, 60, 0)
         g_app_info_launch_uris_async(m_app_info,
                                      l,
                                      nullptr,
                                      nullptr,
                                      nullptr,
                                      nullptr);
+#else
+        g_app_info_launch_uris(m_app_info, l, nullptr, nullptr);
+#endif // GLIB_CHECK_VERSION
         g_list_free(l);
     }
```

The patch is based on `68d90644ecf39c896715792b7fae3eebb88600a1` .

**Comment by Yue-Lan** [comment]
Hi, BLumia

I've patched for your issue manually.

I recommend you create an issue and then send a pull request if possible when you met some problems like this one. Anyway, I really welcome you to participate in this project.

Thank you.
